import React from 'react';
import './ResourcesPage.css';

const resourceData = [

    "An experimental study of self-sensing concrete enhanced with multi-wall carbon nanotubes in wedge splitting test and DIC",
    "Characterization of smart brass fiber reinforced concrete under various loading conditions",
    "Effect of characteristics of assembly unit of CNT/NCB composite fillers on properties of smart cement-based materials",
    "Experimental investigation on mechanical and piezoresistive properties of cementitious materials containing graphene and graphene oxides nanoplatelets",
    "Graphene nanoplatelets as an effective additive to tune the microstructures and piezoresistive properties of cement-based composites",
    "Effect of steel fiber and carbon black on the self-sensing ability of concrete cracks under bending",
    "Effects of carbon nanomaterial type and amount on self-sensing capacity of cement paste",
    "Electrically conductive behaviors and mechanisms of short-cut super-fine stainless wire reinforced reactive powder concrete",
    "Electrically cured ultra-high performance concrete (UHPC) embedded with carbon nanotubes for field casting and crack sensing",
    "Influence of carbon nanofiber content and sodium chloride solution on the stability of resistance and the following self-sensing performance of carbon nanofiber cement paste",
    "Nano graphite platelets-enabled piezoresistive cementitious composites for structural health monitoring",
    "Self-sensing piezoresistive cement composite loaded with carbon black particles",
    "Influence of recycled slag aggregates on the conductivity and strain sensing capacity of carbon fiber reinforced cement mortars",
    "Mechanical, electrical and self-sensing properties of cementitious mortars containing short carbon fibers",
    "Improved strain sensing properties of cement-based sensors through enhanced carbon nanotube dispersion",
    "Increasing self-sensing capability of carbon nanotubes cement-based materials by simultaneous addition of Ni nanofibers with low content",
    "Multifunctional self-sensing and ductile cementitious materials",
    "Self-sensing capability of ultra-high-performance concrete containing steel fibers and carbon nanotubes under tension",
    "Temperature and humidity influence on the strain sensing performance of hybrid carbon nanotubes and graphite cement composites",
    "Effect of aspect ratio on strain sensing capacity of carbon fiber reinforced cement composites",
    "Enhancing self-stress sensing ability of smart ultra-high performance concretes under compression by using nano functional fillers",
    "Smart Infrastructure Monitoring through Self-Sensing Composite Sensors and Systems: A Study on Smart Concrete Sensors with Varying Carbon-Based Filler",
    "Smart Graphite–Cement Composites with Low Percolation Threshold",
    "Hybrid Carbon Microfibers-Graphite Fillers for Piezoresistive Cementitious Composites",
    "Smart Graphite–Cement Composite for Roadway-Integrated Weigh-In-Motion Sensing",
    "Electrical and piezoresistive properties of carbon nanofiber cement mortar under different temperatures and water contents",
    "Self-stress sensing smart concrete containing fine steel slag aggregates and steel fibers under high compressive stress",
    "Intrinsic graphene/cement-based sensors with piezoresistivity and superhydrophobicity capacities for smart concrete infrastructure",
    "Physicochemical and Piezoresistive properties of smart cementitious composites with graphene nanoplates and graphite plates",
    "Self-sensing ultra-high performance concrete for in-situ monitoring",
    "Electrical resistance and capacitance responses of smart ultra-high performance concrete with compressive strain by DC and AC measurements",
    "Piezoresistivity enhancement of functional carbon black filled cement-based sensor using polypropylene fibre",
    "Wireless cement-based sensor for self-monitoring of railway concrete infrastructures",
    "Sensing performance of engineered cementitious composites in different application forms",
    "In-situ synthesizing carbon nanotubes on cement to develop self-sensing cementitious composites for smart high-speed rail infrastructures",
    "Sensing performances of hybrid steel wires and fibers reinforced ultra-high performance concrete for in-situ monitoring of infrastructures",
    "The applicability of shungite as an electrically conductive additive in cement composites",
    "Self-sensing properties and piezoresistive effect of high ductility cementitious composite",
    "Mechanical properties and piezoresistive performances of intrinsic graphene nanoplate/cement-based sensors subjected to impact load",
    "Improving electrical and piezoresistive properties of cement-based composites by combined addition of nano carbon black and nickel nanofiber",
    "Electrical and piezoresistive properties of cement composites with carbon nanomaterials",
    "Influences of multi-walled carbon nanotube (MCNT) fraction, moisture, stress/strain level on the electrical properties of MCNT cement-based composites",
    "Carbon Microfiber-Doped Smart Concrete Sensors for Strain Monitoring in Reinforced Concrete Structures: An Experimental Study at Various Scales",
    "Carbon Nanofibers Grown in CaO for Self-Sensing in Mortar",
    "Electro-mechanical self-sensing response of ultra-high-performance fiber-reinforced concrete in tension",
    "A pressure-sensitive carbon black cement composite for traffic monitoring",
    "Nanocarbon black-based ultra-high-performance concrete (UHPC) with self-strain sensing capability",
    "Self-sensing cementitious composites incorporated with botryoid hybrid nano-carbon materials for smart infrastructures",
    "Investigation on physicochemical and piezoresistive properties of smart MWCNT/cementitious composite exposed to elevated temperatures",
    "Development of self-sensing cementitious composite incorporating hybrid graphene nanoplates and carbon nanotubes for structural health monitoring",
    "Modifying self-sensing cement-based composites through multiscale composition",
    "Study on self-sensing capabilities of smart cements filled with graphene oxide under dynamic cyclic loading",
    "Piezoresistivity, mechanisms and model of cement-based materials with CNT/NCB composite fillers",
    "Multipurpose experimental characterization of smart nanocomposite cement-based materials for thermal-energy efficiency and strain-sensing capability",
    "Piezoresistive properties of cement composites with expanded graphite",
    "Piezoresistive behaviours of cement-based sensor with carbon black subjected to various temperature and water content",
    "Self-sensing properties of Engineered Cementitious Composites",
    "Electrical Properties of Cement-Based Composites with Carbon Nanotubes, Graphene, and Graphite Nanofibers",
    "Research on the self-sensing and mechanical properties of random and aligned stainless steel fiber-reinforced reactive powder concrete",
    "Self-sensing cement-based sensors with superhydrophobic and self-cleaning capacities after silane-based surficial treatments",
    "Self-sensing capabilities of cement-based sensor with layer-distributed conductive rubber fibers",
    "An Experimental Study on Static and Dynamic Strain Sensitivity of Embeddable Smart Concrete Sensors Doped with Carbon Nanotubes for SHM of Large Structures",
    "Experimental Investigation of the Piezoresistive Properties of Cement Composites with Hybrid Carbon Fibers and Nanotubes",
    "Strain and damage sensing properties on multifunctional cement composites with CNF admixture",
    "Effects of different kinds of carbon black nanoparticles on the piezoresistive and mechanical properties of cement-based composites",
    "Cement-based sensors with carbon fibers and carbon nanotubes for piezoresistive sensing",
    "Evaluating the Self-Sensing Ability of Cement Mortars Manufactured with Graphene Nanoplatelets, Virgin or Recycled Carbon Fibers through Piezoresistivity Tests",
    "Enhanced sensing performance of cement-based composites achieved via magnetically aligned nickel particle network",
    "Anisotropic electrical and piezoresistive sensing properties of cement-based sensors with aligned carbon fibers",
    "Development of piezoresistive cement-based sensor using recycled waste glass cullets coated with carbon nanotubes",
    "Strain sensitivity of steel-fiber-reinforced industrial smart concrete",
    "Self sensing carbon nanotube (CNT) and nanofiber (CNF) cementitious composites for real time damage assessment in smart structures",
    "Strain-sensing characteristics of self-consolidating concrete with micro-carbon fiber",
    "Self-sensing performance of cement-based sensor with carbon black and polypropylene fiber subjected to different loading conditions",
    "Mechanical and self-sensing properties of concrete reinforced with carbon nanofibers",
    "Carbon nanotube cement-based transducers for dynamic sensing of strain",
    "Material characterization and piezoresistive sensing capability assessment of thin-walled CNT-embedded ultra-high performance concrete",
    "Piezoresistive properties of ultra-high-performance fiber-reinforced concrete incorporating few-layer graphene",
    "Synthesis, design and piezo-resistive characteristics of cementitious smart nanocomposites with different types of functionalized MWCNTs under long cyclic loading",
    "Effect of compressive strain on electrical resistivity of carbon black-filled cement-based composites",
    "Tailoring sensing properties of smart cementitious composites based on excluded volume theory and electrostatic self-assembly",
    "Performance of cement-based sensors with CNT for strain sensing",
    "Electrostatic self-assembled carbon nanotube/nano carbon black composite fillers reinforced cement-based materials with multifunctionality",
    "Electrical conductivity and piezo-resistive characteristics of CNT and CNF incorporated cementitious nanocomposites under static and dynamic loading",
    "Structural performance of reinforced concrete beams with 3D printed cement-based sensor embedded and self-sensing cementitious composites",
    "Piezoresistivity of carbon fiber graphite cement-based composites with CCCW",
    "Experimental study on use of nickel powder-filled Portland cement-based composite for fabrication of piezoresistive sensors with high sensitivity",
    "A comparative study on the influences of CNT and GNP on the piezoresistivity of cement composites",
    "Research on the self-sensing and mechanical properties of aligned stainless steel fiber-reinforced reactive powder concrete",
    "Enhanced effects of carbon-based conductive materials on the piezoresistive characteristics of cementitious composites",
    "The Utilization of Pearson’s Method to Analyze Piezoresistive Effect in Self-Sensing Cement Composite with Graphite",
    "Self-sensing cementitious composite sensor with integrated steel fiber and carbonaceous powder for real-time application in large-scale infrastructures",
    "Electrical resistance and capacitance responses of smart ultra-high performance concrete with compressive strain by DC and AC measurements",
    "Self-sensing cementitious composites incorporating hybrid NGPs/CNTs/NCBs for structural health monitoring",
    "Self-sensing GFRP-reinforced concrete beams containing carbon nanotube-nano carbon black composite fillers",
    "Microstructural Investigation of the Effects of Carbon Black Nanoparticles on Hydration Mechanisms, Mechanical and Piezoresistive Properties of Cement Mortars",
    "Commercial and recycled carbon-based fillers and fibers for self-sensing cement-based composites: Comparison of mechanical strength, durability, and piezoresistive behavior",
    "Characterization and piezo-resistivity studies on graphite-enabled self-sensing cementitious composites with high stress and strain sensitivity",
];
  const resourceLinks = [
    "https://doi.org/10.1016/j.conbuildmat.2020.120871",
    "https://doi.org/10.1016/j.conbuildmat.2020.120411",
    "https://doi.org/10.1016/j.compositesa.2018.03.020",
    "http://dx.doi.org/10.1016/j.conbuildmat.2016.10.024",
    "https://doi.org/10.1016/j.conbuildmat.2019.03.173",
    "https://doi.org/10.1016/j.conbuildmat.2019.02.160",
    "https://doi.org/10.1016/j.measurement.2018.11.024",
    "https://doi.org/10.1016/j.cemconcomp.2016.05.022",
    "https://doi.org/10.1016/j.matdes.2020.109127",
    "https://doi.org/10.1016/j.cscm.2019.e00247",
    "https://doi.org/10.1016/j.conbuildmat.2017.01.006",
    "https://doi.org/10.1016/j.cemconcomp.2017.04.009",
    "https://doi.org/10.1016/j.conbuildmat.2018.06.218",
    "https://doi.org/10.1016/j.jobe.2018.06.011",
    "https://doi.org/10.1016/j.cemconcomp.2020.103842",
    "https://doi.org/10.1016/j.conbuildmat.2020.119306",
    "https://doi.org/10.1016/j.cemconres.2019.03.008",
    "https://doi.org/10.1016/j.sna.2018.04.009",
    "https://doi.org/10.1016/j.conbuildmat.2021.122786",
    "https://doi.org/10.1016/j.matdes.2013.05.010",
    "https://doi.org/10.1016/j.jobe.2021.102717",
    "https://doi.org/10.3390/infrastructures7040048",
    "https://doi.org/10.3390/ma15082770",
    "https://doi.org/10.3390/s21020518",
    "https://doi.org/10.3390/s20164518",
    "https://doi.org/10.1016/j.conbuildmat.2020.120740",
    "https://doi.org/10.1016/j.conbuildmat.2019.05.197",
    "https://doi.org/10.1016/j.autcon.2021.103983",
    "https://doi.org/10.1016/j.conbuildmat.2021.122943",
    "https://doi.org/10.1016/j.sna.2021.113049",
    "https://doi.org/10.1016/j.conbuildmat.2022.127007",
    "https://doi.org/10.1016/j.powtec.2020.06.029",
    "https://doi.org/10.1016/j.autcon.2020.103323",
    "https://doi.org/10.1016/j.conbuildmat.2022.129223",
    "https://doi.org/10.1016/j.nantod.2022.101438",
    "https://doi.org/10.1016/j.jobe.2022.105022",
    "https://doi.org/10.1016/j.jobe.2021.103469",
    "https://doi.org/10.1016/j.conbuildmat.2022.126390",
    "https://doi.org/10.1016/j.conbuildmat.2022.126978",
    "https://doi.org/10.1016/j.jobe.2022.104312",
    "https://doi.org/10.1177/0021998318764809",
    "https://doi.org/10.1016/j.sna.2018.08.010",
    "https://www.mdpi.com/1424-8220/22/16/6083",
    "https://doi.org/10.3390/ma15144951",
    "https://doi.org/10.1016/j.compositesb.2017.09.061",
    "https://doi.org/10.1016/j.conbuildmat.2017.08.053",
    "https://doi.org/10.1016/j.conbuildmat.2022.129496",
    "https://doi.org/10.1177/1045389X16657416",
    "https://doi.org/10.1016/j.cemconcomp.2020.103675",
    "https://doi.org/10.1016/j.sna.2022.113367",
    "https://doi.org/10.1088/1361-6501/abdfed",
    "https://doi.org/10.1016/j.jobe.2022.104775",
    "https://doi.org/10.1088/2053-1591/aa9d1d",
    "https://doi.org/10.1016/j.solmat.2016.11.030",
    "https://doi.org/10.1016/j.coco.2020.03.005",
    "https://doi.org/10.1016/j.compositesb.2019.107488",
    "https://doi.org/10.1016/j.conbuildmat.2018.04.129",
    "https://doi.org/10.3390/s17051064",
    "https://doi.org/10.1016/j.cemconcomp.2021.104001",
    "https://doi.org/10.1016/j.cscm.2022.e01311",
    "https://doi.org/10.1016/j.sna.2019.111763",
    "https://doi.org/10.3390/s18030831",
    "https://doi.org/10.3390/s17112516",
    "https://doi.org/10.1016/j.cemconcomp.2013.11.009",
    "https://doi.org/10.1016/j.jobe.2020.101724",
    "https://doi.org/10.1016/j.cemconcomp.2012.04.007",
    "https://doi.org/10.3390/su10114013",
    "https://doi.org/10.1016/j.coco.2021.101006",
    "https://doi.org/10.1016/j.cemconcomp.2020.103873",
    "https://doi.org/10.1016/j.jclepro.2021.127968",
    "https://doi.org/10.1177/1045389X19888722",
    "https://doi.org/10.1016/j.cemconcomp.2014.07.003",
    "https://doi.org/10.1080/14488353.2019.1704206",
    "https://doi.org/10.1016/j.jobe.2022.105003",
    "https://doi.org/10.1680/jadcr.18.00209",
    "https://doi.org/10.1016/j.cemconcomp.2012.12.013",
    "https://doi.org/10.1016/j.cemconcomp.2022.104808",
    "https://doi.org/10.1016/j.conbuildmat.2021.124362",
    "https://doi.org/10.1016/j.cemconcomp.2020.103517",
    "https://doi.org/10.1016/j.cemconcomp.2006.05.004",
    "https://doi.org/10.1016/j.conbuildmat.2020.119452",
    "https://doi.org/10.1680/adcr.14.00120",
    "https://doi.org/10.1016/j.compositesa.2015.09.016",
    "https://doi.org/10.1016/j.compositesa.2017.05.018",
    "https://doi.org/10.1016/j.engstruct.2022.115266",
    "https://doi.org/10.1007/s11595-011-0226-0",
    "https://doi.org/10.1016/j.sna.2008.10.001",
    "https://doi.org/10.1016/j.matlet.2019.126858",
    "https://doi.org/10.1016/j.cemconcomp.2021.104001",
    "https://doi.org/10.1016/j.conbuildmat.2022.127804",
    "https://doi.org/10.1590/1980-5373-MR-2022-0051",
    "https://doi.org/10.1016/j.sna.2023.114209",
    "https://doi.org/10.1016/j.conbuildmat.2022.127007",
    "https://doi.org/10.1016/j.sna.2023.114365",
    "https://doi.org/10.1088/1361-6501/accc20",
    "https://doi.org/10.1590/1980-5373-MR-2020-0539",
    "https://doi.org/10.1016/j.jobe.2023.106836",
    "https://doi.org/10.1016/j.cemconcomp.2023.105187"
  ];

  const ResourcesPage = () => {
    return (
      <div className="resources-page">
        <h1>Resources and Further Learning</h1>
        <ul>
          {resourceData.map((title, index) => (
            <li key={index}>
              <a href={resourceLinks[index]} target="_blank" rel="noopener noreferrer">
                {title}
              </a>
            </li>
          ))}
        </ul>
      </div>
    );
  };
  
  export default ResourcesPage;
